scrape_configs:
  - job_name: 'MoviesServerMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.100.12:8080']
        labels:
          application: 'Movies Application'
  - job_name: minio-job
    scrape_interval: 3s
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiZUdWZkJtbDZ6N3Z1eDdPeG95REciLCJleHAiOjQ4ODM0MzU1MzR9.lyQvTnbiKkirNd0iLAKMVTW2OQG1HOo6u3BvM6Hg8lEtRqBENIbVRLtxfdLNt9WQAI_ZoeRIS8tWcU08L1PD7Q
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['192.168.100.12:9000']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '192.168.100.12:9093'

rule_files:
    - minio-alerting.yml