global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'MoviesServerMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['192.168.100.12:8080']
        labels:
          application: 'Movies Application'
  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiUk9PVFVTRVIiLCJleHAiOjQ4ODQ0OTM0NzN9.M-RcXenpLiXRiyob8plLxAX95WHovoUM56nQcIzoA7yc73sQZ3Y-bL3NtYDXmYGnFm_w5PTDpa5jLIDU36NnJQ
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 1m
    scheme: http
    static_configs:
      - targets: ['192.168.100.12:9000']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '192.168.100.12:9093'

rule_files:
    - /etc/prometheus/minio-alerting.yml