scrape_configs:
  - job_name: 'MoviesServerMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:443']
        labels:
          application: 'Movies Application'